### ISSUE TITLE
VS2017 Support

### ISSUE THREAD

**Issue by dylanvdmerwe** [ASP-NET-MVC-Boilerplate/Templates#148]
When VS 2017 RTMs early March, it would be amazing for the new .Net Core project structures to be supported. Amazing template and will provide HuGE value to many people, but definitely needs to support VS 2017.

**Comment by kfrancis** [comment]
Can't even open the generated code in 2017:

![microsoft visual studio 2017-02-21 09 37 25](https://cloud.githubusercontent.com/assets/67574/23169341/63601334-f819-11e6-8c68-58eafaa4c7ef.png)

**Comment by dylanvdmerwe** [comment]
I'm assuming you'll need to create the solution & projects first in VS 2015. Then when you open VS 2017 it will convert to the new .Net Core project structures.

**Comment by kfrancis** [comment]
@dylanvdmerwe Yep, you're right.

**Comment by RehanSaeed** [comment]
VS 2017 support is coming but it's complicated due to the move from `xproj` and `project.json` to `csproj`. With project.json sadly dead, I will be removing the ASP.NET Core template support from VS 2015, moving to `csproj` and adding support for VS 2017 when it comes out in a couple of weeks. I plan to start work on this this/next weekend, any PR's to speed up the process would be welcomed.

I could do some advanced work to support both `xproj` and `csproj` in one VSIX but that is not easy and project.json is sadly now a dead project system.

As an aside, did you guys notice the new [API project template](https://github.com/ASP-NET-MVC-Boilerplate/Templates/blob/master/MVC%206%20API.md) I released which uses the `dotnet new` command line instead of Visual Studio and it's antiquated project template system? The long term plan is to port the other templates to `dotnet new` and then get the VSIX to use the `dotnet new` templates.

**Comment by vip32** [comment]
why not just support vs2017 (csproj) only? VS2017 will release in a couple of weeks and is will be the only 'official/supported' VS to work with .net core onward. MS also has this focus.
it's not ideal, but to keep your great template lean and future proof it might make sense...

**Comment by dylanvdmerwe** [comment]
I would definitely recommend just supporting VS2017 only going forward as soon as it RTMs.

It also seems `dotnet new` is a good way to go.

**Comment by RehanSaeed** [comment]
@vip32 Thats the plan.
@dylanvdmerwe Will move more towards `dotnet new`.

**Comment by RehanSaeed** [comment]
Just a quick update. There is now a VS 2017 branch where I have upgraded all projects. I will see if I can release an update for the `dotnet new` template today. The VSIX is blocked by https://github.com/ligershark/template-builder/issues/96. As soon as the problem with building VSIX's containing the new csproj projects is fixed, I'll do a release.

**Comment by RehanSaeed** [comment]
Another update. The MVC 6 and MVC 6 API project templates are now updated in the VS 2017 branch. VSIX is still blocked on https://github.com/ligershark/template-builder/issues/96. Have not had time to get the `dotnet new` NuGet package released but hopefully within the next couple of days.

**Comment by RehanSaeed** [comment]
I have a VSIX. Unfortunately, after making your feature selections and hitting ok, it kills Visual Studio due to a Visual Studio bug. However, you can just restart Visual Studio and get going. I am considering releasing it with a warning dialog box, what does everyone think?

**Comment by PeterHaro** [comment]
If that is the only problem, please go ahead and release :)

**Comment by RehanSaeed** [comment]
Sorry for the delay, my laptop broke down, I sent it to MSI for repair and 1 month on it's still in Poland and they are asking me to pay almost full price for a replacement :(

I released version 6 today...at last.
